### ISSUE TITLE
requests.exceptions.ReadTimeout

### ISSUE THREAD

**Issue by laryan61** [dgilland/omdb.py#19]
I've switched my Ubuntu system to now use Python 3.5.2. I've been updating my scripts as needed. I'm using the following in my script. This was working under Python 2.7.

from omdb import OMDBClient
client = OMDBClient(apikey = 'xxxxxx')
client.set_default('timeout', 10) #I set this value high during testing

jdata = client.imdbid(text) #I'm passing only the imdb number

This is the error output I get. Any help would be appreciated.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='www.omdbapi.com', port=80): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./movierenamer.py", line 315, in <module>
    IMDB, movie_title, movie_year, movie_foreign = search_movie(movieIMDB)
  File "./movierenamer.py", line 83, in search_movie
    jdata = client.imdbid(text)	#dict
  File "/usr/local/lib/python3.5/dist-packages/omdb/client.py", line 122, in imdbid
    return self.get(imdbid=string, **params)
  File "/usr/local/lib/python3.5/dist-packages/omdb/client.py", line 97, in get
    data = self.request(**params).json()
  File "/usr/local/lib/python3.5/dist-packages/omdb/client.py", line 50, in request
    res = self.session.get(self.url, params=params, timeout=timeout)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='www.omdbapi.com', port=80): Read timed out. (read timeout=10)

**Comment by dgilland** [comment]
Your error message seems to indicate a read timeout from omdbapi.com. Is that issue still happening? Could have been an issue with their site. If you get the timeout error again, you could try running the same script under Python 2.7 to verify whether that one works while 3.5 doesn't.

**Comment by laryan61** [comment]
Doesn’t your API provide graceful exit? Or what is the proper way to use your API to provide a graceful exit if no reply from website?

Thanks,




Lee Ryan
President, NexLynx, Inc
123 SW 6th Ave, Suite 100
Topeka, KS 66603
Tel: 785.232.5969 / Fax: 866.894.7209

[Visit our Facebook Page]<http://www.facbook.com/NexLynxInc>[Visit our Twitter Feed]<http://www.twitter.com/Nexlynx>[Visit our LinkedIn Profile]<https://www.linkedin.com/company/2060059?trk=prof-exp-company-name>

Discover the IT Difference

[Visit our Website]<http://www.nexlynx.com/>
Topeka's Oldest Web Hosting and Web Design Provider<http://www.topekawebdesign.com/>

**Comment by dgilland** [comment]
If an omdbapi.com request fails, an exception will be raised. So putting a try/except around it and handling the error would be the way to go.

All request errors will originate from the `requests` library:

- http://docs.python-requests.org/en/master/user/quickstart/#errors-and-exceptions
- https://github.com/dgilland/omdb.py/blob/9d547bc7dac263b7fb413781dc9830b6248c1625/src/omdb/client.py#L51
